// ══════════════════════════════════════════════════════
//  LYRICSMAP.JS  —  Lyrics registry (statId → .txt path)
// ══════════════════════════════════════════════════════
//
//  HOW IT WORKS
//  ────────────
//  Each key is a track's `statId` (from data.js).
//  Each value is the path to a plain-text lyrics file.
//
//  Path formats accepted:
//    "/lyrics/ALBUM/TRACK.txt"   ← absolute from site root  ✓ (recommended)
//    "lyrics/ALBUM/TRACK.txt"    ← relative to page         ✓
//    "https://cdn.example/…txt"  ← full URL                 ✓
//
//  The lyrics .txt format is parsed by _lyricsParse() in aui.js:
//
//    # Section Name              → bold section header (untimed)
//    :12.5: Lyric line text      → timed line (seconds)
//    :12.5-15.0: Lyric line      → timed line with explicit end
//    :18.0:                      → timed pause (renders as · · ·)
//    (blank lines / other)       → ignored
//
//  To add a new album:
//    1. Add a block below using the statId values from data.js.
//    2. Drop the real .txt files in place of example.txt.
//    3. Done — no changes needed in data.js, audioEngine.js, or aui.js.
// ══════════════════════════════════════════════════════

const LYRICS_MAP = {

  // ── CD ───────────────────────────────────────────────
  "#CD_INTRO":  "example.txt",
  "#CD_WDC":    "example.txt",
  "#CD_GRAD":   "example.txt",
  "#CD_AFD":    "example.txt",
  "#CD_IFA":    "example.txt",
  "#CD_SPACE":  "example.txt",
  "#CD_JW":     "example.txt",
  "#CD_NLMD":   "example.txt",
  "#CD_GEH":    "example.txt",
  "#CD_WPS":    "example.txt",
  "#CD_TNWP":   "example.txt",
  "#CD_SJ":     "example.txt",
  "#CD_BIBO":   "example.txt",
  "#CD_SSS1":   "example.txt",
  "#CD_SS":     "example.txt",
  "#CD_SSS2":   "example.txt",
  "#CD_2W":     "example.txt",
  "#CD_TTW":    "example.txt",
  "#CD_FB":     "example.txt",
  "#CD_LC":     "example.txt",

  // ── LR ───────────────────────────────────────────────
  "#LR_BMD":    "example.txt",
  "#LR_CEL":    "example.txt",
  "#LR_CM":     "example.txt",
  "#LR_DIAM":   "example.txt",
  "#LR_DS":     "example.txt",
  "#LR_GD":     "example.txt",
  "#LR_GONE":   "example.txt",
  "#LR_HES":    "example.txt",
  "#LR_HM":     "example.txt",
  "#LR_LATE":   "example.txt",
  "#LR_ROSES":  "example.txt",
  "#LR_TTS":    "example.txt",
  "#LR_WM":     "example.txt",

  // ── GR ───────────────────────────────────────────────
  "#GR_GM":     "example.txt",
  "#GR_CHAMP":  "example.txt",
  "#GR_STR":    "example.txt",
  "#GR_IW":     "example.txt",
  "#GR_GL":     "example.txt",
  "#GR_CTMN":   "example.txt",
  "#GR_BB":     "example.txt",
  "#GR_DHG":    "example.txt",
  "#GR_FL":     "example.txt",
  "#GR_EIA":    "example.txt",
  "#GR_TG":     "example.txt",
  "#GR_HC":     "example.txt",
  "#GR_BIG":    "example.txt",

  // ── 808 ──────────────────────────────────────────────
  "#808_SYW":   "example.txt",
  "#808_WTH":   "example.txt",
  "#808_HL":    "example.txt",
  "#808_AMAZ":  "example.txt",
  "#808_LL":    "example.txt",
  "#808_PAR":   "example.txt",
  "#808_RC":    "example.txt",
  "#808_SL":    "example.txt",
  "#808_BN":    "example.txt",
  "#808_SYMN":  "example.txt",
  "#808_CW":    "example.txt",
  "#808_PS":    "example.txt",

  // ── WTT ──────────────────────────────────────────────
  "#WTT_NCITW": "example.txt",
  "#WTT_LO":    "example.txt",
  "#WTT_NIP":   "example.txt",
  "#WTT_OTIS":  "example.txt",
  "#WTT_GHI":   "example.txt",
  "#WTT_ND":    "example.txt",
  "#WTT_TMB":   "example.txt",
  "#WTT_WTTJ":  "example.txt",
  "#WTT_WGSM":  "example.txt",
  "#WTT_MTE":   "example.txt",
  "#WTT_WILY":  "example.txt",
  "#WTT_HAM":   "example.txt",
  "#WTT_PT":    "example.txt",
  "#WTT_TJ":    "example.txt",

  // ── CS ───────────────────────────────────────────────
  "#CS_TTW":    "example.txt",
  "#CS_CLIQUE": "example.txt",
  "#CS_MERCY":  "example.txt",
  "#CS_NGF":    "example.txt",
  "#CS_TM":     "example.txt",
  "#CS_COLD":   "example.txt",
  "#CS_HIGH":   "example.txt",
  "#CS_SC":     "example.txt",
  "#CS_CREEP":  "example.txt",
  "#CS_BLISS":  "example.txt",
  "#CS_DL":     "example.txt",

  // ── YZ ───────────────────────────────────────────────
  "#YZ_OS":     "example.txt",
  "#YZ_BSH":    "example.txt",
  "#YZ_IAAG":   "example.txt",
  "#YZ_NS":     "example.txt",
  "#YZ_HML":    "example.txt",
  "#YZ_III":    "example.txt",
  "#YZ_BOTL":   "example.txt",
  "#YZ_GT":     "example.txt",
  "#YZ_SIU":    "example.txt",
  "#YZ_B2":     "example.txt",

  // ── YE ───────────────────────────────────────────────
  "#YE_ITAKY":  "example.txt",
  "#YE_YK":     "example.txt",
  "#YE_AM":     "example.txt",
  "#YE_WL":     "example.txt",
  "#YE_NM":     "example.txt",
  "#YE_GT":     "example.txt",
  "#YE_VC":     "example.txt",

  // ── KSG ──────────────────────────────────────────────
  "#KSG_FTL":   "example.txt",
  "#KSG_FIRE":  "example.txt",
  "#KSG_4D":    "example.txt",
  "#KSG_FREE":  "example.txt",
  "#KSG_REB":   "example.txt",
  "#KSG_KSG":   "example.txt",
  "#KSG_CM":    "example.txt",

  // ── JIK ──────────────────────────────────────────────
  "#JIK_EH":    "example.txt",
  "JIK_SEL":    "example.txt",
  "#JIK_FG":    "example.txt",
  "#JIK_COS":   "example.txt",
  "#JIK_OG":    "example.txt",
  "#JIK_EWN":   "example.txt",
  "#JIK_WAT":   "example.txt",
  "#JIK_GI":    "example.txt",
  "#JIK_HO":    "example.txt",
  "#JIK_UTG":   "example.txt",
  "#JIK_JIL":   "example.txt",

  // ── DON ──────────────────────────────────────────────
  "#DON_DC":    "example.txt",
  "#DON_JAIL":  "example.txt",
  "#DON_GB":    "example.txt",
  "#DON_OTG":   "example.txt",
  "#DON_HUR":   "example.txt",
  "#DON_PG":    "example.txt",
  "#DON_JON":   "example.txt",
  "#DON_OO":    "example.txt",
  "#DON_JUN":   "example.txt",
  "#DON_BWIS":  "example.txt",
  "#DON_24":    "example.txt",
  "#DON_RC":    "example.txt",
  "#DON_MOON":  "example.txt",
  "#DON_HAH":   "example.txt",
  "#DON_DON":   "example.txt",
  "#DON_PS":    "example.txt",
  "#DON_CTL":   "example.txt",
  "#DON_NCLB":  "example.txt",
  "#DON_JAIL2": "example.txt",
  "#DON_JL":    "example.txt",
  "#DON_NA":    "example.txt",
  "#DON_TTV":   "example.txt",
  "#DON_LINY":  "example.txt",

  // ── D2 ───────────────────────────────────────────────
  "#D2_SF":     "example.txt",
  "#D2_TL":     "example.txt",
  "#D2_SEC":    "example.txt",
  "#D2_TE":     "example.txt",
  "#D2_LB":     "example.txt",
  "#D2_PAB":    "example.txt",
  "#D2_RF":     "example.txt",
  "#D2_HAP":    "example.txt",
  "#D2_WDIK":   "example.txt",
  "#D2_FLW":    "example.txt",

  // ── V1 ───────────────────────────────────────────────
  "#V1_VUL":    "example.txt",
  "#V1_PAID":   "example.txt",
  "#V1_HR":     "example.txt",
  "#V1_TALK":   "example.txt",
  "#V1_CARN":   "example.txt",
  "#V1_BURN":   "example.txt",
  "#V1_KING":   "example.txt",
  "#V1_KTML":   "example.txt",
  "#V1_PROB":   "example.txt",
  "#V1_GDD":    "example.txt",
  "#V1_DI":     "example.txt",
  "#V1_BF":     "example.txt",
  "#V1_PW":     "example.txt",
  "#V1_BTM":    "example.txt",
  "#V1_V2":     "example.txt",
  "#V1_LS":     "example.txt",

  // ── V2 ───────────────────────────────────────────────
  "#V2_FT":     "example.txt",
  "#V2_EVB":    "example.txt",
  "#V2_BOMB":   "example.txt",
  "#V2_RIV":    "example.txt",
  "#V2_SCI":    "example.txt",
  "#V2_MUNCH":  "example.txt",
  "#V2_DRV":    "example.txt",
  "#V2_MAST":   "example.txt",
  "#V2_BEG":    "example.txt",
  "#V2_LR":     "example.txt",
  "#V2_GTMH":   "example.txt",
  "#V2_PM":     "example.txt",
  "#V2_SLD":    "example.txt",
  "#V2_FD":     "example.txt",

  // ── BUL ──────────────────────────────────────────────
  "#BUL_BATB":             "example.txt",
  "#BUL_BULLY":            "example.txt",
  "#BUL_CANT_HURRY_LOVE":  "example.txt",
  "#BUL_CIRCLES":          "example.txt",
  "#BUL_DAMN":             "example.txt",
  "#BUL_HIGHS_AND_LOWS":   "example.txt",
  "#BUL_LAST_BREATH":      "example.txt",
  "#BUL_LOSING_YOUR_MIND": "example.txt",
  "#BUL_MISSION_CONTROL":  "example.txt",
  "#BUL_PEOPLE_LIKE_ME":   "example.txt",
  "#BUL_PREACHER_MAN":     "example.txt",
  "#BUL_THIS_ONE_HERE":    "example.txt",
  "#BUL_WHITE_LINES":      "example.txt",

  // ── DL ───────────────────────────────────────────────
  "#DL_LT":     "example.txt",
  "#DL_RIP":    "example.txt",
  "#DL_L4R":    "example.txt",
  "#DL_OM":     "example.txt",
  "#DL_LH":     "example.txt",
  "#DL_SHOOT":  "example.txt",
  "#DL_RN":     "example.txt",
  "#DL_PIO":    "example.txt",
  "#DL_HOME":   "example.txt",
  "#DL_FIL":    "example.txt",
  "#DL_FOR":    "example.txt",
  "#DL_PU":     "example.txt",
  "#DL_MIL":    "example.txt",
  "#DL_FF":     "example.txt",
  "#DL_NT":     "example.txt",
  "#DL_MOTS":   "example.txt",
  "#DL_CWM":    "example.txt",
  "#DL_RIPF":   "example.txt",
  "#DL_TOP":    "example.txt",

  // ── GOB ──────────────────────────────────────────────
  "#GOB_GOB":   "example.txt",
  "#GOB_YON":   "example.txt",
  "#GOB_RAD":   "example.txt",
  "#GOB_SHE":   "example.txt",
  "#GOB_TRANS": "example.txt",
  "#GOB_NIGHT": "example.txt",
  "#GOB_TC":    "example.txt",
  "#GOB_HER":   "example.txt",
  "#GOB_SAND":  "example.txt",
  "#GOB_FISH":  "example.txt",
  "#GOB_ANA":   "example.txt",
  "#GOB_BSD":   "example.txt",
  "#GOB_WIN":   "example.txt",
  "#GOB_AU79":  "example.txt",
  "#GOB_GOLD":  "example.txt",

  // ── WOLF ─────────────────────────────────────────────
  "#WOLF_WOLF": "example.txt",
  "#WOLF_JAM":  "example.txt",
  "#WOLF_COW":  "example.txt",
  "#WOLF_AWK":  "example.txt",
  "#WOLF_D23":  "example.txt",
  "#WOLF_ANS":  "example.txt",
  "#WOLF_SLA":  "example.txt",
  "#WOLF_48":   "example.txt",
  "#WOLF_COL":  "example.txt",
  "#WOLF_PIOC": "example.txt",
  "#WOLF_PCB":  "example.txt",
  "#WOLF_IFHY": "example.txt",
  "#WOLF_PIGS": "example.txt",
  "#WOLF_PL":   "example.txt",
  "#WOLF_RUS":  "example.txt",
  "#WOLF_TW":   "example.txt",
  "#WOLF_TH95": "example.txt",
  "#WOLF_TAM":  "example.txt",
  "#WOLF_LONE": "example.txt",

  // ── CB ───────────────────────────────────────────────
  "#CB_DC":     "example.txt",
  "#CB_BUF":    "example.txt",
  "#CB_PIL":    "example.txt",
  "#CB_RUN":    "example.txt",
  "#CB_FYW":    "example.txt",
  "#CB_CB":     "example.txt",
  "#CB_BML":    "example.txt",
  "#CB_2S":     "example.txt",
  "#CB_BS":     "example.txt",
  "#CB_FYP":    "example.txt",
  "#CB_SMU":    "example.txt",
  "#CB_KDO":    "example.txt",
  "#CB_OKA":    "example.txt",

  // ── FB ───────────────────────────────────────────────
  "#FB_FORE":   "example.txt",
  "#FB_WTFB":   "example.txt",
  "#FB_SOM":    "example.txt",
  "#FB_SYA":    "example.txt",
  "#FB_WDB":    "example.txt",
  "#FB_POT":    "example.txt",
  "#FB_GS":     "example.txt",
  "#FB_BOR":    "example.txt",
  "#FB_IAGT":   "example.txt",
  "#FB_911":    "example.txt",
  "#FB_DS":     "example.txt",
  "#FB_NOV":    "example.txt",
  "#FB_GLI":    "example.txt",
  "#FB_ERNT":   "example.txt",

  // ── IGOR ─────────────────────────────────────────────
  "#IGOR_IT":    "example.txt",
  "#IGOR_EQ":    "example.txt",
  "#IGOR_ITK":   "example.txt",
  "#IGOR_EWYRF": "example.txt",
  "#IGOR_ROOT":  "example.txt",
  "#IGOR_NMW":   "example.txt",
  "#IGOR_ABIAG": "example.txt",
  "#IGOR_PUP":   "example.txt",
  "#IGOR_WG":    "example.txt",
  "#IGOR_GGTY":  "example.txt",
  "#IGOR_IDLYA": "example.txt",
  "#IGOR_AWSF":  "example.txt",

  // ── CMIYGL ───────────────────────────────────────────
  "#CMIYGL_SB":   "example.txt",
  "#CMIYGL_COR":  "example.txt",
  "#CMIYGL_LEM":  "example.txt",
  "#CMIYGL_WUS":  "example.txt",
  "#CMIYGL_LUM":  "example.txt",
  "#CMIYGL_HWB":  "example.txt",
  "#CMIYGL_MAS":  "example.txt",
  "#CMIYGL_RUN":  "example.txt",
  "#CMIYGL_MAN":  "example.txt",
  "#CMIYGL_SWE":  "example.txt",
  "#CMIYGL_MT":   "example.txt",
  "#CMIYGL_RISE": "example.txt",
  "#CMIYGL_BLE":  "example.txt",
  "#CMIYGL_JUG":  "example.txt",
  "#CMIYGL_WIL":  "example.txt",
  "#CMIYGL_SAF":  "example.txt",

  // ── TES ──────────────────────────────────────────────
  "#TES_EMG":   "example.txt",
  "#TES_STU":   "example.txt",
  "#TES_WAD":   "example.txt",
  "#TES_WT":    "example.txt",
  "#TES_DOG":   "example.txt",
  "#TES_HTM":   "example.txt",
  "#TES_BG":    "example.txt",

  // ── CHK ──────────────────────────────────────────────
  "#CHK_SC":    "example.txt",
  "#CHK_NOID":  "example.txt",
  "#CHK_IKY":   "example.txt",
  "#CHK_TWD":   "example.txt",
  "#CHK_LH":    "example.txt",
  "#CHK_DI":    "example.txt",
  "#CHK_HJ":    "example.txt",
  "#CHK_BAL":   "example.txt",
  "#CHK_LPL":   "example.txt",
  "#CHK_WTD":   "example.txt",
  "#CHK_ER":    "example.txt",
  "#CHK_FAN":   "example.txt",
  "#CHK_OUT":   "example.txt",

  // ── DTTG ─────────────────────────────────────────────
  "#DTTG_BP":    "example.txt",
  "#DTTG_SOT":   "example.txt",
  "#DTTG_SF":    "example.txt",
  "#DTTG_MOM":   "example.txt",
  "#DTTG_SPWM":  "example.txt",
  "#DTTG_RRR":   "example.txt",
  "#DTTG_DTT":   "example.txt",
  "#DTTG_DYWB":  "example.txt",
  "#DTTG_ITCOY": "example.txt",
  "#DTTG_TMWII": "example.txt",

  // ── S80 ──────────────────────────────────────────────
  "#S80_FYE":   "example.txt",
  "#S80_HU":    "example.txt",
  "#S80_ADHD":  "example.txt",
  "#S80_NMU":   "example.txt",
  "#S80_TS":    "example.txt",
  "#S80_C6":    "example.txt",
  "#S80_RRE":   "example.txt",
  "#S80_PMD":   "example.txt",
  "#S80_TSC":   "example.txt",
  "#S80_C10":   "example.txt",
  "#S80_KS":    "example.txt",
  "#S80_RIG":   "example.txt",
  "#S80_KC":    "example.txt",
  "#S80_BMH":   "example.txt",
  "#S80_ASO":   "example.txt",
  "#S80_HP":    "example.txt",

  // ── GKMC ─────────────────────────────────────────────
  "#GKMC_S":     "example.txt",
  "#GKMC_BDKMV": "example.txt",
  "#GKMC_BF":    "example.txt",
  "#GKMC_AOPP":  "example.txt",
  "#GKMC_MT":    "example.txt",
  "#GKMC_PJ":    "example.txt",
  "#GKMC_GK":    "example.txt",
  "#GKMC_MC":    "example.txt",
  "#GKMC_SP":    "example.txt",
  "#GKMC_SAM":   "example.txt",
  "#GKMC_REAL":  "example.txt",
  "#GKMC_COMP":  "example.txt",

  // ── TPAB ─────────────────────────────────────────────
  "#TPAB_WT":   "example.txt",
  "#TPAB_FF":   "example.txt",
  "#TPAB_KK":   "example.txt",
  "#TPAB_INST": "example.txt",
  "#TPAB_TW":   "example.txt",
  "#TPAB_U":    "example.txt",
  "#TPAB_ALR":  "example.txt",
  "#TPAB_MM":   "example.txt",

  // ── DAMN ─────────────────────────────────────────────
  "#DAMN_BLOOD":   "example.txt",
  "#DAMN_DNA":     "example.txt",
  "#DAMN_YAH":     "example.txt",
  "#DAMN_ELEMENT": "example.txt",
  "#DAMN_FEEL":    "example.txt",
  "#DAMN_LOYALTY": "example.txt",
  "#DAMN_PRIDE":   "example.txt",
  "#DAMN_HUMBLE":  "example.txt",
  "#DAMN_LUST":    "example.txt",
  "#DAMN_LOVE":    "example.txt",
  "#DAMN_XXX":     "example.txt",
  "#DAMN_FEAR":    "example.txt",
  "#DAMN_GOD":     "example.txt",
  "#DAMN_DUCK":    "example.txt",

  // ── LIR ──────────────────────────────────────────────
  "#LIR_SAFE_HOUSE": "example.txt",
  "#LIR_ENEMIES":    "example.txt",
  "#LIR_WSM":        "example.txt",
  "#LIR_RIGHT_NOW":  "example.txt",
  "#LIR_AMC":        "example.txt",
  "#LIR_NNY21":      "example.txt",
  "#LIR_YAMB":       "example.txt",
  "#LIR_BLEED":      "example.txt",
  "#LIR_TITLE":      "example.txt",

  // ── LUVTW ────────────────────────────────────────────
  "#LUVTW_CANADA":  "example.txt",
  "#LUVTW_HIROLLER":"example.txt",
  "#LUVTW_ML":      "example.txt",
  "#LUVTW_PSQS":    "example.txt",
  "#LUVTW_YWR":     "example.txt",
  "#LUVTW_BAYH":    "example.txt",
  "#LUVTW_SAR":     "example.txt",
  "#LUVTW_TWLG":    "example.txt",
  "#LUVTW_FORREAL": "example.txt",

  // ── EA (#) ───────────────────────────────────────────
  "#EA_BABY_PLUTO":  "example.txt",
  "#EA_LO_MEIN":     "example.txt",
  "#EA_SILLY_WATCH": "example.txt",
  "#EA_POP":         "example.txt",
  "#EA_YBM":         "example.txt",
  "#EA_HOMECOMING":  "example.txt",
  "#EA_ICSY":        "example.txt",
  "#EA_VENETIA":     "example.txt",
  "#EA_STB":         "example.txt",
  "#EA_PRICES":      "example.txt",
  "#EA_URGENCY":     "example.txt",
  "#EA_CSTATION":    "example.txt",
  "#EA_BTL":         "example.txt",
  "#EA_CHT":         "example.txt",
  "#EA_BUST_ME":     "example.txt",
  "#EA_THAT_WAY":    "example.txt",
  "#EA_P2":          "example.txt",

  // ── LVTW2 ────────────────────────────────────────────
  "#LVTW2_MYRON":      "example.txt",
  "#LVTW2_LOTUS":      "example.txt",
  "#LVTW2_BEAN":       "example.txt",
  "#LVTW2_YESSIR":     "example.txt",
  "#LVTW2_WASSUP":     "example.txt",
  "#LVTW2_SP":         "example.txt",
  "#LVTW2_MOON":       "example.txt",
  "#LVTW2_CTW":        "example.txt",
  "#LVTW2_TTW":        "example.txt",
  "#LVTW2_GTG":        "example.txt",
  "#LVTW2_LEADERS":    "example.txt",
  "#LVTW2_BABY_PLUTO": "example.txt",
  "#LVTW2_P2":         "example.txt",

  // ── PT ───────────────────────────────────────────────
  "#PT_FLOODED":  "example.txt",
  "#PT_SUICIDE":  "example.txt",
  "#PT_AYE":      "example.txt",
  "#PT_CRUSH":    "example.txt",
  "#PT_AMPED":    "example.txt",
  "#PT_X2":       "example.txt",
  "#PT_DIED":     "example.txt",
  "#PT_SPIN":     "example.txt",
  "#PT_FIYA":     "example.txt",
  "#PT_IGOTTA":   "example.txt",
  "#PT_ENDLESS":  "example.txt",
  "#PT_MAMA":     "example.txt",
  "#PT_ALONE":    "example.txt",
  "#PT_NAKAMURA": "example.txt",
  "#PT_JWR":      "example.txt",
  "#PT_PATIENCE": "example.txt",
  "#PT_CS":       "example.txt",
  "#PT_WEREWOLF": "example.txt",
  "#PT_PLUTO":    "example.txt",
  "#PT_DAYS":     "example.txt",
  "#PT_REHAB":    "example.txt",
  "#PT_THE_END":  "example.txt",

  // ── RD ───────────────────────────────────────────────
  "#RD_PORNOGRAPHY":        "example.txt",
  "#RD_OH_MY_DIS_SIDE":     "example.txt",
  "#RD_3500":               "example.txt",
  "#RD_WASTED":             "example.txt",
  "#RD_90210":              "example.txt",
  "#RD_PRAY_4_LOVE":        "example.txt",
  "#RD_NIGHTCRAWLER":       "example.txt",
  "#RD_PISS_ON_YOUR_GRAVE": "example.txt",
  "#RD_ANTIDOTE":           "example.txt",
  "#RD_IMPOSSIBLE":         "example.txt",
  "#RD_MARIA_IM_DRUNK":     "example.txt",
  "#RD_FLYING_HIGH":        "example.txt",
  "#RD_I_CAN_TELL":         "example.txt",
  "#RD_APPLE_PIE":          "example.txt",
  "#RD_OK_ALRIGHT":         "example.txt",
  "#RD_NEVER_CATCH_ME":     "example.txt",

  // ── DBR ──────────────────────────────────────────────
  "#DBR_THE_PRAYER":              "example.txt",
  "#DBR_MAMACITA":                "example.txt",
  "#DBR_QUINTANA_PT_2":           "example.txt",
  "#DBR_DRUGS_YOU_SHOULD_TRY_IT": "example.txt",
  "#DBR_DONT_PLAY":               "example.txt",
  "#DBR_SKYFALL":                 "example.txt",
  "#DBR_ZOMBIES":                 "example.txt",
  "#DBR_SLOPPY_TOPPY":            "example.txt",
  "#DBR_BASEMENT_FREESTYLE":      "example.txt",
  "#DBR_BACKYARD":                "example.txt",
  "#DBR_GREY":                    "example.txt",
  "#DBR_BACC":                    "example.txt",

  // ── BITTSMK ──────────────────────────────────────────
  "#BITTSMK_THE_ENDS":              "example.txt",
  "#BITTSMK_WAY_BACK":              "example.txt",
  "#BITTSMK_COORDINATE":            "example.txt",
  "#BITTSMK_THROUGH_THE_LATE_NIGHT":"example.txt",
  "#BITTSMK_BEIBS_IN_THE_TRAP":     "example.txt",
  "#BITTSMK_SDP_INTERLUDE":         "example.txt",
  "#BITTSMK_SWEET_SWEET":           "example.txt",
  "#BITTSMK_OUTSIDE":               "example.txt",
  "#BITTSMK_GOOSEBUMPS":            "example.txt",
  "#BITTSMK_FIRST_TAKE":            "example.txt",
  "#BITTSMK_PICK_UP_THE_PHONE":     "example.txt",
  "#BITTSMK_LOSE":                  "example.txt",
  "#BITTSMK_GUIDANCE":              "example.txt",
  "#BITTSMK_WONDERFUL":             "example.txt",

  // ── JB ───────────────────────────────────────────────
  "#JB_HIGHEST_IN_THE_ROOM_REMIX": "example.txt",
  "#JB_GANG_GANG":  "example.txt",
  "#JB_HAD_ENOUGH": "example.txt",
  "#JB_OUT_WEST":   "example.txt",
  "#JB_WHAT_TO_DO": "example.txt",
  "#JB_GATTI":      "example.txt",
  "#JB_JACKBOYS":   "example.txt",

  // ── JB2 ──────────────────────────────────────────────
  "#JB2_CHAMPAGNE_AND_VACAY": "example.txt",
  "#JB2_2000_EXCURSION":      "example.txt",
  "#JB2_IN_MY_HEAD":          "example.txt",
  "#JB2_GANG_2":              "example.txt",
  "#JB2_POPPIN_AGAIN":        "example.txt",
  "#JB2_4X4":                 "example.txt",
  "#JB2_DO_IT_FOR_THE_GANG":  "example.txt",
  "#JB2_OVERSEAS_MOTION":     "example.txt",
  "#JB2_TOO_GEEKED":          "example.txt",
  "#JB2_BACK_OUTSIDE":        "example.txt",
  "#JB2_VICTORY_LAP":         "example.txt",
  "#JB2_THE_FINISH_LINE":     "example.txt",

  // ── ST ───────────────────────────────────────────────
  "#ST_FLEX":          "example.txt",
  "#ST_HAD2":          "example.txt",
  "#ST_HALFANDHALF":   "example.txt",
  "#ST_KELLYK":        "example.txt",
  "#ST_LAMENIGGAZ":    "example.txt",
  "#ST_LETITGO":       "example.txt",
  "#ST_LOCATION":      "example.txt",
  "#ST_LOOKIN":        "example.txt",
  "#ST_MAGNOLIA":      "example.txt",
  "#ST_NO9":           "example.txt",
  "#ST_NEWCHOPPA":     "example.txt",
  "#ST_OTHERSHIT":     "example.txt",
  "#ST_YAHMEAN":       "example.txt",
  "#ST_DOTHATSHIT":    "example.txt",
  "#ST_WOKEUPLIKETHIS":"example.txt",

  // ── OD ───────────────────────────────────────────────
  "#OD_MYOLDMAN":           "example.txt",
  "#OD_THISOLDDOG":         "example.txt",
  "#OD_BABYYOUREOUT":       "example.txt",
  "#OD_FORTHEFIRSTTIME":    "example.txt",
  "#OD_ONEANOTHER":         "example.txt",
  "#OD_STILLBEATING":       "example.txt",
  "#OD_SISTER":             "example.txt",
  "#OD_DREAMSFROMYESTERDAY":"example.txt",
  "#OD_WOLF":               "example.txt",
  "#OD_ONEMORELOVESONG":    "example.txt",
  "#OD_ONTHELEVEL":         "example.txt",
  "#OD_MOONLIGHT":          "example.txt",
  "#OD_WATCHINGHIM":        "example.txt",
  "#OD_INTRO":              "example.txt",
  "#OD_DOOMSDAY":           "example.txt",
  "#OD_RHYMESLIKEDIMES":    "example.txt",
  "#OD_THEFINEST":          "example.txt",
  "#OD_BACKINDAYS":         "example.txt",
  "#OD_GOWITHTHEFLOW":      "example.txt",
  "#OD_TICKTICK":           "example.txt",
  "#OD_REDANDGOLD":         "example.txt",
  "#OD_HANDSOFDOOM":        "example.txt",
  "#OD_WHOYOUTHINK":        "example.txt",
  "#OD_AREYOUAWAKE":        "example.txt",
  "#OD_HEY":                "example.txt",
  "#OD_GREENBACKS":         "example.txt",
  "#OD_THEMIC":             "example.txt",
  "#OD_MYSTERY":            "example.txt",
  "#OD_DEADBENT":           "example.txt",
  "#OD_GASDRAWLS":          "example.txt",
  "#OD_QUESTION":           "example.txt",
  "#OD_EPILOGUE":           "example.txt",

  // ── MMFOOD ───────────────────────────────────────────
  "#MMFOOD_BEEFRAPP":  "example.txt",
  "#MMFOOD_HOECAKES":  "example.txt",
  "#MMFOOD_POTHOLDERZ":"example.txt",
  "#MMFOOD_ONEBEER":   "example.txt",
  "#MMFOOD_DEEPFRIED": "example.txt",
  "#MMFOOD_POOPUTT":   "example.txt",
  "#MMFOOD_FILLETO":   "example.txt",
  "#MMFOOD_GUMBO":     "example.txt",
  "#MMFOOD_FIGLEAF":   "example.txt",
  "#MMFOOD_KONKARNE":  "example.txt",
  "#MMFOOD_GUINNESSES":"example.txt",
  "#MMFOOD_KONQUESO":  "example.txt",
  "#MMFOOD_RAPPSNITCH":"example.txt",
  "#MMFOOD_VOMITSPIT": "example.txt",
  "#MMFOOD_KOOKIES":   "example.txt",

  // ── BLT ──────────────────────────────────────────────
  "#BLT_INTRO":         "example.txt",
  "#BLT_GAZZILLION":    "example.txt",
  "#BLT_BALLSKIN":      "example.txt",
  "#BLT_YESSIR":        "example.txt",
  "#BLT_ABSOLUTELY":    "example.txt",
  "#BLT_RAPAMBUSH":     "example.txt",
  "#BLT_LIGHTWORKS":    "example.txt",
  "#BLT_BATTYBOYZ":     "example.txt",
  "#BLT_ANGELZ":        "example.txt",
  "#BLT_CELLZ":         "example.txt",
  "#BLT_STILLDOPE":     "example.txt",
  "#BLT_MICROWAVEMAYO": "example.txt",
  "#BLT_MORERHYMIN":    "example.txt",
  "#BLT_THATSTHAT":     "example.txt",
  "#BLT_SUPERVILLAINZ": "example.txt",
  "#BLT_BUMPYSMESSAGE": "example.txt",

  // ── TMTYL ────────────────────────────────────────────
  "#TMTYL_FAZERS":      "example.txt",
  "#TMTYL_FASTLANE":    "example.txt",
  "#TMTYL_KRAZYWORLD":  "example.txt",
  "#TMTYL_LOCKJAW":     "example.txt",
  "#TMTYL_NEXTLEVELS":  "example.txt",
  "#TMTYL_NOSNAKES":    "example.txt",
  "#TMTYL_ANTIMATTER":  "example.txt",
  "#TMTYL_FINEPRINT":   "example.txt",
  "#TMTYL_ONESMART":    "example.txt",
  "#TMTYL_THEMIC":      "example.txt",
  "#TMTYL_FINALHOUR":   "example.txt",
  "#TMTYL_MONSTERZERO": "example.txt",
  "#TMTYL_WHOSMAN":     "example.txt",

  // ── MV ───────────────────────────────────────────────
  "#MV_ILLEST":      "example.txt",
  "#MV_ACCORDION":   "example.txt",
  "#MV_MEATGRINDER": "example.txt",
  "#MV_BISTRO":      "example.txt",
  "#MV_RAID":        "example.txt",
  "#MV_AMERICAS":    "example.txt",
  "#MV_SICKFIT":     "example.txt",
  "#MV_RAINBOWS":    "example.txt",
  "#MV_CURLS":       "example.txt",
  "#MV_DONOTFIRE":   "example.txt",
  "#MV_MONEYFOLDER": "example.txt",
  "#MV_SHADOWS":     "example.txt",
  "#MV_LIFESAVER":   "example.txt",
  "#MV_FIGARO":      "example.txt",
  "#MV_HARDCORE":    "example.txt",
  "#MV_STRANGEWAYS": "example.txt",
  "#MV_FANCYCLOWN":  "example.txt",
  "#MV_EYE":         "example.txt",
  "#MV_THEME":       "example.txt",
  "#MV_ALLCAPS":     "example.txt",
  "#MV_GREUNDAY":    "example.txt",
  "#MV_RHINESTONE":  "example.txt",

  // ── MM (#) ───────────────────────────────────────────
  "#MM_CHUPA":       "example.txt",
  "#MM_SOFAKING":    "example.txt",
  "#MM_MASK":        "example.txt",
  "#MM_PERFECTHAIR": "example.txt",
  "#MM_BENZIE":      "example.txt",
  "#MM_OLDSCHOOL":   "example.txt",
  "#MM_ATHF":        "example.txt",
  "#MM_BASKET":      "example.txt",
  "#MM_NONAMES":     "example.txt",
  "#MM_CROSSHAIRS":  "example.txt",
  "#MM_MINCEMEAT":   "example.txt",
  "#MM_VATS":        "example.txt",
  "#MM_SPACEHOS":    "example.txt",
  "#MM_BADABING":    "example.txt",

  // ── VV ───────────────────────────────────────────────
  "#VV_OVERTURE":               "example.txt",
  "#VV_VAUDEVILLE_VILLAIN":     "example.txt",
  "#VV_LICKUPON":               "example.txt",
  "#VV_THE_DROP":               "example.txt",
  "#VV_LACTOSE_AND_LECITHIN":   "example.txt",
  "#VV_A_DEAD_MOUSE":           "example.txt",
  "#VV_OPEN_MIC_NITE_PT_1":     "example.txt",
  "#VV_RAEDAWN":                "example.txt",
  "#VV_LET_ME_WATCH":           "example.txt",
  "#VV_SALIVA":                 "example.txt",
  "#VV_MODERN_DAY_MUGGING":     "example.txt",
  "#VV_OPEN_MIC_NITE_PT_2":     "example.txt",
  "#VV_NEVER_DEAD":             "example.txt",
  "#VV_POPSNOT":                "example.txt",
  "#VV_MR_CLEAN":               "example.txt",
  "#VV_GMC":                    "example.txt",
  "#VV_CHANGE_THE_BEAT":        "example.txt",
  "#VV_VENOMOUS_VILLAIN_INTRO": "example.txt",
  "#VV_BACK_END":               "example.txt",
  "#VV_RAP_GAME":               "example.txt",
  "#VV_DOPE_SKILL":             "example.txt",
  "#VV_ODE_TO_ROAD_RAGE":       "example.txt",
  "#VV_BLOODY_CHAIN":           "example.txt",
  "#VV_DETENTION":              "example.txt",
  "#VV_CAN_I_WATCH":            "example.txt",
  "#VV_OG":                     "example.txt",
  "#VV_DOPER_SKILLER":          "example.txt",
  "#VV_GREAT_DAY":              "example.txt",
  "#VV_THE_FINE_PRINT":         "example.txt",
  "#VV_A_DEAD_MOUSE_REMIX":     "example.txt",
  "#VV_POP_QUIZ":               "example.txt",

  // ── CM ───────────────────────────────────────────────
  "#CM_TAKE_YOUR_MEDICINE":       "example.txt",
  "#CM_MEDDLE_WITH_METAL":        "example.txt",
  "#CM_BADNESS_OF_MADNESS":       "example.txt",
  "#CM_PHANTOMS":                 "example.txt",
  "#CM_BOMB_THROWN":              "example.txt",
  "#CM_CAPTAIN_CRUNCH":           "example.txt",
  "#CM_MASTRR_OF_DISGUISE":       "example.txt",
  "#CM_ASTRAL_TRAVELING":         "example.txt",
  "#CM_DEFINITION_OF_A_RAP_FLOW": "example.txt",
  "#CM_YOU_KNOW_MY_STYLE":        "example.txt",
  "#CM_MIC_CHECK":                "example.txt",
  "#CM_THIS_IS_CANON_NOW":        "example.txt",

  // ── SW (Czarface) ─────────────────────────────────────
  "#SW_THE_KING_AND_EYE":                       "example.txt",
  "#SW_CZARWYNS_THEORY_OF_PEOPLE_GETTING_LOOSE":"example.txt",
  "#SW_MANDO_CALRISSIAN":                       "example.txt",
  "#SW_DOOM_UNTO_OTHERS":                       "example.txt",
  "#SW_JASON_AND_THE_CZARGONAUTS":              "example.txt",
  "#SW_BREAK_IN_THE_ACTION":                    "example.txt",
  "#SW_A_NAME_TO_THE_FACE":                     "example.txt",
  "#SW_THIS_IS_CANON_NOW":                      "example.txt",
  "#SW_SO_STRANGE":                             "example.txt",
  "#SW_YOUNG_WORLD":                            "example.txt",

  // ── X ────────────────────────────────────────────────
  "#X_DELINQUENT":    "example.txt",
  "#X_FREESTYLE_1":   "example.txt",
  "#X_FREESTYLE_2":   "example.txt",
  "#X_FUK12":         "example.txt",
  "#X_GEMS":          "example.txt",
  "#X_GET_RICH_OR_DIE":"example.txt",
  "#X_GO":            "example.txt",
  "#X_GOING_SCHITZ":  "example.txt",
  "#X_INTRO":         "example.txt",
  "#X_MDMA":          "example.txt",
  "#X_MONEY_HUNT":    "example.txt",
  "#X_MURDA_MUSIK":   "example.txt",
  "#X_NEW":           "example.txt",
  "#X_NOBODY":        "example.txt",
  "#X_PDBMH":         "example.txt",
  "#X_SAME_THING":    "example.txt",
  "#X_SOUTH_BEACH":   "example.txt",
  "#X_THE_END":       "example.txt",
  "#X_TURN_UP":       "example.txt",
  "#X_X":             "example.txt",

  // ── AG ───────────────────────────────────────────────
  "#AG_FIGHTING_MY_DEMONS": "example.txt",
  "#AG_GREEN_ROOM":         "example.txt",
  "#AG_HARDCORE":           "example.txt",
  "#AG_ITS_OVER":           "example.txt",
  "#AG_JENNIFERS_BODY":     "example.txt",
  "#AG_LIKE_THIS":          "example.txt",
  "#AG_LOSE_IT":            "example.txt",
  "#AG_ME_N_MY_KUP":        "example.txt",
  "#AG_NIGHTCORE_2":        "example.txt",
  "#AG_NIGHTCORE":          "example.txt",
  "#AG_OVERTIME":           "example.txt",
  "#AG_PARANOID":           "example.txt",
  "#AG_POTS":               "example.txt",
  "#AG_ROCKSTAR_LIFESTYLE":  "example.txt",
  "#AG_SINGAPORE":          "example.txt",
  "#AG_SUCCUBUS":           "example.txt",
  "#AG_VAMPIRE_HOUR":       "example.txt",
  "#AG_I_NEED_U":           "example.txt",
  "#AG_LEATHER_JACKET":     "example.txt",
  "#AG_LOADING":            "example.txt",
  "#AG_MEWTWO":             "example.txt",
  "#AG_MORE_CHAOS":         "example.txt",
  "#AG_OVERSEAS":           "example.txt",
  "#AG_SS":                 "example.txt",
  "#AG_TOXIC":              "example.txt",

  // ── IL ───────────────────────────────────────────────
  "#IL_IF_LOOKS_COULD_KILL":   "example.txt",
  "#IL_HOW_U_FEEL":            "example.txt",
  "#IL_FLY_SHT":               "example.txt",
  "#IL_WHICH_WAY":             "example.txt",
  "#IL_RAVER":                 "example.txt",
  "#IL_CAME_IN_WIT":           "example.txt",
  "#IL_BY_THE_POUND":          "example.txt",
  "#IL_RIGHT_NOW":             "example.txt",
  "#IL_WHICH_ONE":             "example.txt",
  "#IL_BRAZY_GIRLS":           "example.txt",
  "#IL_MOMENT_OF_SILENCE":     "example.txt",
  "#IL_SUPERSTAR":             "example.txt",
  "#IL_NEW_NEW":               "example.txt",
  "#IL_SAFETY_INTERLUDE":      "example.txt",
  "#IL_YOUR_EYES":             "example.txt",
  "#IL_MONEY_AND_SEX":         "example.txt",
  "#IL_WORTH_IT":              "example.txt",
  "#IL_PROMO":                 "example.txt",
  "#IL_PASSENGER":             "example.txt",
  "#IL_MAKE_SUM_WORK":         "example.txt",
  "#IL_WHICH_ONE_BONUS":       "example.txt",
  "#IL_MONEY_AND_SEX_BONUS":   "example.txt",
  "#IL_MOMENT_OF_SILENCE_BONUS":"example.txt",
  "#IL_BY_THE_POUND_BONUS":    "example.txt",
  "#IL_FLY_SHT_BONUS":         "example.txt",
  "#IL_HOW_U_FEEL_BONUS":      "example.txt",

  // ── LL ───────────────────────────────────────────────
  "#LL_FOREVER":       "example.txt",
  "#LL_LOVE_HURTS":    "example.txt",
  "#LL_STAY_FOREVER":  "example.txt",
  "#LL_CRYSTAL_CLEAR": "example.txt",
  "#LL_DREAM_GIRL":    "example.txt",
  "#LL_NO_WORRIES":    "example.txt",
  "#LL_HOLD_ON":       "example.txt",
  "#LL_STARS_ALIGN":   "example.txt",
  "#LL_NEVER_LET_GO":  "example.txt",
  "#LL_AFTERGLOW":     "example.txt",
  "#LL_LAST_NIGHT":    "example.txt",
  "#LL_FALL_AGAIN":    "example.txt",
  "#LL_PALACE":        "example.txt",
  "#LL_PESO":          "example.txt",
  "#LL_BASS":          "example.txt",
  "#LL_WASSUP":        "example.txt",
  "#LL_BRAND_NEW_GUY": "example.txt",
  "#LL_PURPLE_SWAG":   "example.txt",
  "#LL_GET_LIT":       "example.txt",
  "#LL_TRILLA":        "example.txt",
  "#LL_KEEP_IT_G":     "example.txt",
  "#LL_HOUSTON_OLD_HEAD":"example.txt",
  "#LL_ACID_DRIP":     "example.txt",
  "#LL_LEAF":          "example.txt",
  "#LL_ROLL_ONE_UP":   "example.txt",
  "#LL_DEMONS":        "example.txt",
  "#LL_OUT_OF_THIS_WORLD":"example.txt",
  "#LL_SANDMAN":       "example.txt",

  // ── HL ───────────────────────────────────────────────
  "#HL_LIFESTYLE":         "example.txt",
  "#HL_DRAKON":            "example.txt",
  "#HL_TRIPPING":          "example.txt",
  "#HL_BIG_O_SHIT":        "example.txt",
  "#HL_STUNT":             "example.txt",
  "#HL_ALL_ON_ME":         "example.txt",
  "#HL_B5":                "example.txt",
  "#HL_SHOOT":             "example.txt",
  "#HL_LIF3":              "example.txt",
  "#HL_5UNNA":             "example.txt",
  "#HL_NOTICE_IT":         "example.txt",
  "#HL_HOMIXIDE":          "example.txt",
  "#HL_SNOTTY_RUN":        "example.txt",
  "#HL_FREE_AGENTS":       "example.txt",
  "#HL_RICH_FLEX":         "example.txt",
  "#HL_MAJOR_DISTRIBUTION":"example.txt",
  "#HL_ON_BS":             "example.txt",
  "#HL_BACKOUTSIDEBOYZ":   "example.txt",
  "#HL_PRIVILEGED_RAPPERS":"example.txt",
  "#HL_SPIN_BOUT_U":       "example.txt",
  "#HL_HOURS_IN_SILENCE":  "example.txt",
  "#HL_TREACHEROUS_TWINS": "example.txt",
  "#HL_CIRCO_LOCO":        "example.txt",
  "#HL_PUSSY_AND_MILLIONS":"example.txt",
  "#HL_BROKE_BOYS":        "example.txt",
  "#HL_MIDDLE_OF_THE_OCEAN":"example.txt",
  "#HL_JUMBOTRON_SHIT_POPPIN":"example.txt",
  "#HL_MORE_MS":           "example.txt",
  "#HL_3AM_ON_GLENWOOD":   "example.txt",
  "#HL_I_GUESS_ITS_FUCK_ME":"example.txt",

  // ── 5A ───────────────────────────────────────────────
  "#5A_5TH_AMNDMNT": "example.txt",
  "#5A_REBEL":       "example.txt",
  "#5A_STEP":        "example.txt",
  "#5A_MASK_UP":     "example.txt",
  "#5A_BLOCK_BABY":  "example.txt",
  "#5A_CRASH_OUT":   "example.txt",
  "#5A_NO_HOOK":     "example.txt",
  "#5A_RIOT":        "example.txt",
  "#5A_DEAD_END":    "example.txt",
  "#5A_ALL_BLACK":   "example.txt",
  "#5A_GANG_TIES":   "example.txt",
  "#5A_OUTRO":       "example.txt",

  // ── SW (Snotty World) ────────────────────────────────
  "#SW_SNOTTY_WORLD":  "example.txt",
  "#SW_VACCINE":       "example.txt",
  "#SW_BIG_HOMIXIDE":  "example.txt",
  "#SW_DRILL":         "example.txt",
  "#SW_5UNNA":         "example.txt",
  "#SW_RACKS":         "example.txt",
  "#SW_GANGSTA_PARTY": "example.txt",
  "#SW_SHOTS":         "example.txt",
  "#SW_NOTICE_IT":     "example.txt",
  "#SW_SNOTTY_RUN":    "example.txt",
  "#SW_LIFESTYLE":     "example.txt",
  "#SW_HOMIXIDE":      "example.txt",
  "#SW_STUNT":         "example.txt",
  "#SW_BLOCK_WORK":    "example.txt",
  "#SW_TRENCH":        "example.txt",

  // ── I5 ───────────────────────────────────────────────
  "#I5_I5U5WE5":       "example.txt",
  "#I5_WOKE_UP":       "example.txt",
  "#I5_STEP_2":        "example.txt",
  "#I5_MONEY_UP":      "example.txt",
  "#I5_GANG_FLOW":     "example.txt",
  "#I5_CRASH":         "example.txt",
  "#I5_ROLL_OUT":      "example.txt",
  "#I5_BLOCK_BABY_2":  "example.txt",
  "#I5_STACK_HIGH":    "example.txt",
  "#I5_TURN_UP_AGAIN": "example.txt",
  "#I5_GANG_SHIT":     "example.txt",
  "#I5_OUTRO":         "example.txt",

  // ── LO ───────────────────────────────────────────────
  "#LO_LONG_LIVE_ASAP":       "example.txt",
  "#LO_GOLDIE":               "example.txt",
  "#LO_PMW_ALL_I_REALLY_NEED":"example.txt",
  "#LO_LVL":                  "example.txt",
  "#LO_HELL":                 "example.txt",
  "#LO_PAIN":                 "example.txt",
  "#LO_FUCKIN_PROBLEMS":      "example.txt",
  "#LO_WILD_FOR_THE_NIGHT":   "example.txt",
  "#LO_1TRAIN":               "example.txt",
  "#LO_FASHION_KILLA":        "example.txt",
  "#LO_PHOENIX":              "example.txt",
  "#LO_SUDDENLY":             "example.txt",

  // ── AL ───────────────────────────────────────────────
  "#AL_HOLY_GHOST":               "example.txt",
  "#AL_CANAL_ST":                 "example.txt",
  "#AL_FINE_WHINE":               "example.txt",
  "#AL_LSD":                      "example.txt",
  "#AL_EXCUSE_ME":                "example.txt",
  "#AL_JD":                       "example.txt",
  "#AL_LORD_PRETTY_FLACKO_JODYE_2":"example.txt",
  "#AL_ELECTRIC_BODY":            "example.txt",
  "#AL_JUKEBOX_JOINTS":           "example.txt",
  "#AL_MAX_B":                    "example.txt",
  "#AL_PHARSYDE":                 "example.txt",
  "#AL_WAVYBONE":                 "example.txt",
  "#AL_WEST_SIDE_HIGHWAY":        "example.txt",
  "#AL_BETTER_THINGS":            "example.txt",
  "#AL_MS":                       "example.txt",
  "#AL_DREAMS_INTERLUDE":         "example.txt",
  "#AL_EVERYDAY":                 "example.txt",
  "#AL_BACK_HOME":                "example.txt",

  // ── TE ───────────────────────────────────────────────
  "#TE_DISTORTED_RECORDS":        "example.txt",
  "#TE_ASAP_FOREVER_REMIX":       "example.txt",
  "#TE_TONY_TONE":                "example.txt",
  "#TE_FUKK_SLEEP":               "example.txt",
  "#TE_PRAISE_THE_LORD_DA_SHINE": "example.txt",
  "#TE_CALLDROPS":                "example.txt",
  "#TE_BUCK_SHOTS":               "example.txt",
  "#TE_GUNZ_N_BUTTER":            "example.txt",
  "#TE_BROTHA_MAN":               "example.txt",
  "#TE_OG_BEEPER":                "example.txt",
  "#TE_KIDS_TURNED_OUT_FINE":     "example.txt",
  "#TE_HUN43RD":                  "example.txt",
  "#TE_CHANGES":                  "example.txt",
  "#TE_BLACK_TUX_WHITE_COLLAR":   "example.txt",
  "#TE_PURITY":                   "example.txt",

  // ── LN ───────────────────────────────────────────────
  "#LN_LORDS_NEVER_WORRY":  "example.txt",
  "#LN_FULL_METAL_JACKET":  "example.txt",
  "#LN_BATH_SALT":          "example.txt",
  "#LN_PUT_THAT_ON_MY_SET": "example.txt",
  "#LN_BLACK_MANE":         "example.txt",
  "#LN_WORK_REMIX":         "example.txt",
  "#LN_TRAP_LORD":          "example.txt",
  "#LN_JAY_REED":           "example.txt",
  "#LN_CHOPPAS_ON_DECK":    "example.txt",
  "#LN_YNRE":               "example.txt",
  "#LN_PURPLE_KISSES":      "example.txt",
  "#LN_BANGIN_ON_WAXX":     "example.txt",
  "#LN_UNDERGROUND_KILLAS": "example.txt",
  "#LN_RIOT_RAVE":          "example.txt",
  "#LN_FREEZE":             "example.txt",
  "#LN_DOPE_MONEY_HOES":    "example.txt",

  // ── CT ───────────────────────────────────────────────
  "#CT_YAMBORGHINI_HIGH":    "example.txt",
  "#CT_CRAZY_BRAZY":         "example.txt",
  "#CT_WAY_HII":             "example.txt",
  "#CT_YOUNG_NIGGA_LIVING":  "example.txt",
  "#CT_TELEPHONE_CALLS":     "example.txt",
  "#CT_STATIC":              "example.txt",
  "#CT_BLACK_CARD":          "example.txt",
  "#CT_LONDON_TOWN":         "example.txt",
  "#CT_RUNNER":              "example.txt",
  "#CT_BACHELOR":            "example.txt",
  "#CT_MONEY_MAN":           "example.txt",
  "#CT_PUT_THAT_ON_MY_SET":  "example.txt",
  "#CT_COZY_TAPAS":          "example.txt",
  "#CT_PERRY_AYE":           "example.txt",
  "#CT_PLEASE_SHUT_UP":      "example.txt",
  "#CT_WALK_ON_WATER":       "example.txt",
  "#CT_RAF":                 "example.txt",
  "#CT_FRAT_RULES":          "example.txt",
  "#CT_FYBR":                "example.txt",
  "#CT_BAHAMAS":             "example.txt",
  "#CT_MONEY_BAGS_FREESTYLE":"example.txt",
  "#CT_GET_THE_BAG":         "example.txt",
  "#CT_WRONG":               "example.txt",
  "#CT_ARIES":               "example.txt",
  "#CT_WHAT_HAPPENS":        "example.txt",
  "#CT_MADE_MAN":            "example.txt",

  // ── OT ───────────────────────────────────────────────
  "#OT_HI":                "example.txt",
  "#OT_FOREST_GREEN":      "example.txt",
  "#OT_WHITE":             "example.txt",
  "#OT_RELLA":             "example.txt",
  "#OT_ANALOG_2":          "example.txt",
  "#OT_BITCHES":           "example.txt",
  "#OT_NY_NED_FLANDER":    "example.txt",
  "#OT_YA_KNOW":           "example.txt",
  "#OT_WE_GOT_BITCHES":    "example.txt",
  "#OT_P":                 "example.txt",
  "#OT_50":                "example.txt",
  "#OT_OLDIE":             "example.txt",
  "#OT_REAL_BITCH":        "example.txt",
  "#OT_SAM_IS_DEAD":       "example.txt",
  "#OT_DOMS":              "example.txt",
  "#OT_LEAN":              "example.txt",
  "#OT_ROLLING_PAPERS":    "example.txt",
  "#OT_BROWN_STAINS_REMIX":"example.txt",

  // ── CO ───────────────────────────────────────────────
  "#CO_START":            "example.txt",
  "#CO_THINKIN_BOUT_YOU": "example.txt",
  "#CO_FERTILIZER":       "example.txt",
  "#CO_SIERRA_LEONE":     "example.txt",
  "#CO_SWEET_LIFE":       "example.txt",
  "#CO_NOT_JUST_MONEY":   "example.txt",
  "#CO_SUPER_RICH_KIDS":  "example.txt",
  "#CO_PILOT_JONES":      "example.txt",
  "#CO_CRACK_ROCK":       "example.txt",
  "#CO_PYRAMIDS":         "example.txt",
  "#CO_LOST":             "example.txt",
  "#CO_WHITE":            "example.txt",
  "#CO_MONKS":            "example.txt",
  "#CO_BAD_RELIGION":     "example.txt",
  "#CO_PINK_MATTER":      "example.txt",
  "#CO_FORREST_GUMP":     "example.txt",
  "#CO_END":              "example.txt",

  // ── EN ───────────────────────────────────────────────
  "#EN_DEVICE_CONTROL":    "example.txt",
  "#EN_AT_YOUR_BEST":      "example.txt",
  "#EN_ALABAMA":           "example.txt",
  "#EN_MINE":              "example.txt",
  "#EN_UNITY":             "example.txt",
  "#EN_AMBIENCE_001":      "example.txt",
  "#EN_COMME_DES_GARCONS": "example.txt",
  "#EN_AMBIENCE_002":      "example.txt",
  "#EN_WITHER":            "example.txt",
  "#EN_HUBLOTS":           "example.txt",
  "#EN_AMBIENCE_003":      "example.txt",
  "#EN_SLIDE_ON_ME":       "example.txt",
  "#EN_SIDEWAYS":          "example.txt",
  "#EN_FLORIDA":           "example.txt",
  "#EN_IMPIETAS_DEATHWISH":"example.txt",
  "#EN_RUSHES":            "example.txt",
  "#EN_RUSHES_TO":         "example.txt",
  "#EN_HIGGS":             "example.txt",

  // ── BL ───────────────────────────────────────────────
  "#BL_NIKES":          "example.txt",
  "#BL_IVY":            "example.txt",
  "#BL_PINK_WHITE":     "example.txt",
  "#BL_BE_YOURSELF":    "example.txt",
  "#BL_SOLO":           "example.txt",
  "#BL_SKYLINE_TO":     "example.txt",
  "#BL_SELF_CONTROL":   "example.txt",
  "#BL_GOOD_GUY":       "example.txt",
  "#BL_NIGHTS":         "example.txt",
  "#BL_SOLO_REPRISE":   "example.txt",
  "#BL_PRETTY_SWEET":   "example.txt",
  "#BL_FACEBOOK_STORY": "example.txt",
  "#BL_CLOSE_TO_YOU":   "example.txt",
  "#BL_WHITE_FERRARI":  "example.txt",
  "#BL_SEIGFRIED":      "example.txt",
  "#BL_GODSPEED":       "example.txt",
  "#BL_FUTURA_FREE":    "example.txt",

  // ── UP ───────────────────────────────────────────────
  "#UP_TWIZZY_RICH":     "example.txt",
  "#UP_U_COULD_TELL":    "example.txt",
  "#UP_MORNING_MUDD":    "example.txt",
  "#UP_GOT_RICH":        "example.txt",
  "#UP_MONEY_SO_BIG":    "example.txt",
  "#UP_FACTZ":           "example.txt",
  "#UP_TURBAN":          "example.txt",
  "#UP_HEY":             "example.txt",
  "#UP_STAYED_THA_SAME": "example.txt",
  "#UP_YA_YA":           "example.txt",
  "#UP_TRENDY_WAY":      "example.txt",
  "#UP_TONKA_2":         "example.txt",
  "#UP_CALLIN_ME":       "example.txt",
  "#UP_CMON":            "example.txt",
  "#UP_LYING_4_FUN":     "example.txt",
  "#UP_BED_SIDE":        "example.txt",
  "#UP_BAK_ON_EM":       "example.txt",
  "#UP_ROKSTAR":         "example.txt",
  "#UP_SWERVED_IT":      "example.txt",
  "#UP_LET_YA_KNOW":     "example.txt",
  "#UP_DESERVE_IT":      "example.txt",
  "#UP_KANT_CHANGE":     "example.txt",

  // ── 2A ───────────────────────────────────────────────
  "#2A_POPPIN":        "example.txt",
  "#2A_OUTSIDE":       "example.txt",
  "#2A_RACKS_GOT_ME":  "example.txt",
  "#2A_JUMP":          "example.txt",
  "#2A_DNT_LIE":       "example.txt",
  "#2A_ROLLIN":        "example.txt",
  "#2A_TALIBAN":       "example.txt",
  "#2A_NVR_AGAIN":     "example.txt",
  "#2A_LUH_M":         "example.txt",
  "#2A_RACKZ_GOT_ME":  "example.txt",
  "#2A_DOUBLE":        "example.txt",
  "#2A_ON_THA_LINE":   "example.txt",
  "#2A_JUS_BETTER":    "example.txt",
  "#2A_STILL_COUNTIN": "example.txt",
  "#2A_BIG_TONKA":     "example.txt",
  "#2A_KANT_RELAX":    "example.txt",
  "#2A_NO_COMMENT":    "example.txt",
  "#2A_SMOOKTOBER":    "example.txt",
  "#2A_CALL_ME":       "example.txt",
  "#2A_LUH_GEEK":      "example.txt",

  // ── AF ───────────────────────────────────────────────
  "#AF_NO_MORE_TALK":  "example.txt",
  "#AF_SHMUNK":        "example.txt",
  "#AF_BETTR_OFF":     "example.txt",
  "#AF_RAV3_P4RTY":    "example.txt",
  "#AF_NUN_ID_CHANGE": "example.txt",
  "#AF_WOA":           "example.txt",
  "#AF_NOW":           "example.txt",
  "#AF_SLAMM":         "example.txt",
  "#AF_7_NIGHTZ":      "example.txt",
  "#AF_MEAN_FEEN":     "example.txt",
  "#AF_HOW_IT_GO":     "example.txt",
  "#AF_SUM_2_DO":      "example.txt",
  "#AF_BACK_HOME":     "example.txt",
  "#AF_TYPE_MONEY":    "example.txt",
  "#AF_BAD_BEND_DEMON":"example.txt",
  "#AF_SPLIT":         "example.txt",
  "#AF_HEAVYWEIGHT":   "example.txt",
  "#AF_WATCH":         "example.txt",
  "#AF_SHHHH":         "example.txt",
  "#AF_BACK_UP":       "example.txt",
  "#AF_DEMON_TIED":    "example.txt",
  "#AF_MYSELF":        "example.txt",

  // ── 20 ───────────────────────────────────────────────
  "#20_PSYCHOCAINE":     "example.txt",
  "#20_POWER_TRIP":      "example.txt",
  "#20_BREATHE":         "example.txt",
  "#20_MORE":            "example.txt",
  "#20_U_SHOULD_KNOW":   "example.txt",
  "#20_RUN_THEY_MOUTH":  "example.txt",
  "#20_IF_WE_BEING_REAL":"example.txt",
  "#20_TELL_ME":         "example.txt",
  "#20_SHADE":           "example.txt",
  "#20_KEEP_PUSHIN":     "example.txt",
  "#20_TEAM_CEO":        "example.txt",
  "#20_1093":            "example.txt",

  // ── SM ───────────────────────────────────────────────
  "#SM_JUST_HOW_IT_IS":        "example.txt",
  "#SM_SUP_MATE":              "example.txt",
  "#SM_ECSTASY":               "example.txt",
  "#SM_HOT":                   "example.txt",
  "#SM_LIGHT_IT_UP":           "example.txt",
  "#SM_SURF":                  "example.txt",
  "#SM_BAD_BAD_BAD":           "example.txt",
  "#SM_LIL_BABY":              "example.txt",
  "#SM_WHATS_THE_MOVE":        "example.txt",
  "#SM_I_BOUGHT_HER":          "example.txt",
  "#SM_JUMPED_OUT_THE_WINDOW": "example.txt",
  "#SM_IM_SCARED":             "example.txt",
  "#SM_CARTIER_GUCCI_SCARF":   "example.txt",
  "#SM_BIG_TIPPER":            "example.txt",
  "#SM_PUSSY":                 "example.txt",
  "#SM_CIRCLE_OF_BOSSES":      "example.txt",
  "#SM_MANNEQUIN_CHALLENGE":   "example.txt",
  "#SM_BOY_BACK":              "example.txt",
  "#SM_THE_LONDON":            "example.txt",

  // ── PU ───────────────────────────────────────────────
  "#PU_DIE_SLOW":              "example.txt",
  "#PU_STRESSED":              "example.txt",
  "#PU_STUPID_ASKING":         "example.txt",
  "#PU_RECOGNIZE_REAL":        "example.txt",
  "#PU_CONTAGIOUS":            "example.txt",
  "#PU_PEEPIN_OUT_THE_WINDOW": "example.txt",
  "#PU_RICH_N_SHIT":           "example.txt",
  "#PU_LIVIN_IT_UP":           "example.txt",
  "#PU_YEA_YEA_YEA":           "example.txt",
  "#PU_INSURE_MY_WRIST":       "example.txt",
  "#PU_SCOLIOSIS":             "example.txt",
  "#PU_BUBBLY":                "example.txt",
  "#PU_ROAD_RAGE":             "example.txt",
  "#PU_FACES":                 "example.txt",
  "#PU_DROPPIN_JEWELS":        "example.txt",
  "#PU_FIFTH_DAY_DEAD":        "example.txt",
  "#PU_ICY_HOT":               "example.txt",
  "#PU_LOVE_YOU_MORE":         "example.txt",
  "#PU_HATE_THE_GAME":         "example.txt",
  "#PU_DAY_BEFORE":            "example.txt",

  // ── BI ───────────────────────────────────────────────
  "#BI_PARADE_ON_CLEVELAND": "example.txt",
  "#BI_MONEY_ON_THE_DRESSER":"example.txt",
  "#BI_GUCCI_GROCERY_BAG":   "example.txt",
  "#BI_CARS_BRING_ME_OUT":   "example.txt",
  "#BI_UNCLE_M":             "example.txt",
  "#BI_ABRACADABRA":         "example.txt",
  "#BI_WENT_THRU_IT":        "example.txt",
  "#BI_OH_U_WENT":           "example.txt",
  "#BI_WANT_ME_DEAD":        "example.txt",
  "#BI_MAD_DOG":             "example.txt",
  "#BI_JONESBORO":           "example.txt",
  "#BI_GLOBAL_ACCESS":       "example.txt",
  "#BI_SAKE_OF_MY_KIDS":     "example.txt",
  "#BI_MOMMA_IM_SORRY":      "example.txt",
  "#BI_WIT_DA_RACKS":        "example.txt",

  // ── PL ───────────────────────────────────────────────
  "#PL_TURN_ON_THE_LIGHTS":   "example.txt",
  "#PL_YOU_DESERVE_IT":       "example.txt",
  "#PL_SAME_DAMN_TIME":       "example.txt",
  "#PL_LONG_LIVE_THE_PIMP":   "example.txt",
  "#PL_HOW_IT_WAS":           "example.txt",
  "#PL_MY":                   "example.txt",
  "#PL_NEVA_END":             "example.txt",
  "#PL_TONY_MONTANA":         "example.txt",
  "#PL_STRAIGHT_UP":          "example.txt",
  "#PL_ASTRONAUT_CHICK":      "example.txt",
  "#PL_MAGIC":                "example.txt",
  "#PL_PERMANENT_SCAR":       "example.txt",
  "#PL_TRUTH_GONNA_HURT_YOU": "example.txt",
  "#PL_DIAMONDS_FROM_AFRICA": "example.txt",
  "#PL_GONE_TO_THE_MOON":     "example.txt",
  "#PL_SAME_DAMN_TIME_REMIX": "example.txt",

  // ── HO ───────────────────────────────────────────────
  "#HO_LOOK_AHEAD":        "example.txt",
  "#HO_HONEST":            "example.txt",
  "#HO_SHIT":              "example.txt",
  "#HO_I_WON":             "example.txt",
  "#HO_NEVER_SATISFIED":   "example.txt",
  "#HO_SIDE_EFFECTS":      "example.txt",
  "#HO_STRAIGHT_UP":       "example.txt",
  "#HO_SAME_DAMN_TIME":    "example.txt",
  "#HO_BENZ_FRIENDZ":      "example.txt",
  "#HO_BLOW_A_BAG":        "example.txt",
  "#HO_T_SHIRT":           "example.txt",
  "#HO_MOVE_THAT_DOPE":    "example.txt",
  "#HO_MY_MOMMA":          "example.txt",
  "#HO_SPECIAL":           "example.txt",
  "#HO_COVERED_N_MONEY":   "example.txt",
  "#HO_BLOOD_SWEAT_TEARS": "example.txt",
  "#HO_HONEST_REMIX":      "example.txt",

  // ── ENTERGALACTIC ────────────────────────────────────
  "#ENTERGALACTIC_THEME":     "example.txt",
  "#ENTERGALACTIC_NEWMODE":   "example.txt",
  "#ENTERGALACTIC_DOWHATIWANT":"example.txt",
  "#ENTERGALACTIC_ANGEL":     "example.txt",
  "#ENTERGALACTIC_IGNITE":    "example.txt",
  "#ENTERGALACTIC_INLOVE":    "example.txt",
  "#ENTERGALACTIC_WILLING":   "example.txt",
  "#ENTERGALACTIC_CANTSHAKE": "example.txt",
  "#ENTERGALACTIC_LOOKIN":    "example.txt",
  "#ENTERGALACTIC_MYDRUG":    "example.txt",
  "#ENTERGALACTIC_FLY":       "example.txt",
  "#ENTERGALACTIC_BURROW":    "example.txt",
  "#ENTERGALACTIC_TORTURED":  "example.txt",
  "#ENTERGALACTIC_TRUTH":     "example.txt",
  "#ENTERGALACTIC_MAYBESO":   "example.txt",

  // ── INSANO ───────────────────────────────────────────
  "#INSANO_OFTEN":           "example.txt",
  "#INSANO_KEEPBOUNCIN":     "example.txt",
  "#INSANO_GETOFFME":        "example.txt",
  "#INSANO_MOSTAINT":        "example.txt",
  "#INSANO_WOW":             "example.txt",
  "#INSANO_ELECTROWAVE":     "example.txt",
  "#INSANO_TOODAMNHIGH":     "example.txt",
  "#INSANO_GETCHAGONE":      "example.txt",
  "#INSANO_ATTHEPARTY":      "example.txt",
  "#INSANO_MRCOOLA":         "example.txt",
  "#INSANO_FRESHIE":         "example.txt",
  "#INSANO_TORTURED":        "example.txt",
  "#INSANO_XANDCUD":         "example.txt",
  "#INSANO_SEVEN":           "example.txt",
  "#INSANO_FUNKYWIZARD":     "example.txt",
  "#INSANO_RAGERBOYZ":       "example.txt",
  "#INSANO_PORSCHE":         "example.txt",
  "#INSANO_BLUESKY":         "example.txt",
  "#INSANO_NIKES":           "example.txt",
  "#INSANO_IJWAG":           "example.txt",
  "#INSANO_NITRO_SUPERBOY":  "example.txt",
  "#INSANO_NITRO_DOSE":      "example.txt",
  "#INSANO_NITRO_MOSTAINT":  "example.txt",
  "#INSANO_NITRO_WOW":       "example.txt",
  "#INSANO_NITRO_ELECTROWAVE":"example.txt",
  "#INSANO_NITRO_ANIMATE":   "example.txt",
  "#INSANO_NITRO_ROUND":     "example.txt",
  "#INSANO_NITRO_RAGER":     "example.txt",
  "#INSANO_NITRO_IJWAG":     "example.txt",
  "#INSANO_NITRO_BLUESKY":   "example.txt",
  "#INSANO_NITRO_NIKES":     "example.txt",
  "#INSANO_NITRO_ANOTHERDAY":"example.txt",
  "#INSANO_NITRO_ROCKET":    "example.txt",
  "#INSANO_NITRO_CHUNKY":    "example.txt",
  "#INSANO_NITRO_FRESHIE":   "example.txt",
  "#INSANO_NITRO_TORTURED":  "example.txt",
  "#INSANO_NITRO_SEVEN":     "example.txt",
  "#INSANO_NITRO_ALLMYLIFE": "example.txt",

  // ── WLR ──────────────────────────────────────────────
  "#WLR_BENO":            "example.txt",
  "#WLR_CONTROL":         "example.txt",
  "#WLR_DIE4GUY":         "example.txt",
  "#WLR_FEEL_LIKE_DYIN":  "example.txt",
  "#WLR_GO2DAMOON":       "example.txt",
  "#WLR_ILOVEUIHATEU":    "example.txt",
  "#WLR_JUMPOUTTHEHOUSE": "example.txt",
  "#WLR_KING_VAMP":       "example.txt",
  "#WLR_M3TAMORPHOSIS":   "example.txt",
  "#WLR_MEH":             "example.txt",
  "#WLR_NEW_N3ON":        "example.txt",
  "#WLR_NEW_TANK":        "example.txt",
  "#WLR_NO_SL33P":        "example.txt",
  "#WLR_NOT_PLAYING":     "example.txt",
  "#WLR_ON_THAT_TIME":    "example.txt",
  "#WLR_OVER":            "example.txt",
  "#WLR_PLACE":           "example.txt",
  "#WLR_PUNK_MONK":       "example.txt",
  "#WLR_ROCKSTAR_MADE":   "example.txt",
  "#WLR_SKY":             "example.txt",
  "#WLR_SLAY3R":          "example.txt",
  "#WLR_STOP_BREATHING":  "example.txt",
  "#WLR_TEEN_X":          "example.txt",
  "#WLR_VAMP_ANTHEM":     "example.txt",

  // ── RRNC ─────────────────────────────────────────────
  "#RRNC_TITLE":          "example.txt",
  "#RRNC_PIPE":           "example.txt",
  "#RRNC_BLUEJEANS":      "example.txt",
  "#RRNC_ONEMORETEAR":    "example.txt",
  "#RRNC_VEGAS":          "example.txt",
  "#RRNC_ONLYYOU":        "example.txt",
  "#RRNC_MOVINGLIKEMIKE": "example.txt",
  "#RRNC_MEANDMINE":      "example.txt",

  // ── TWO ──────────────────────────────────────────────
  "#TWO_COOKING":      "example.txt",
  "#TWO_DREAMING":     "example.txt",
  "#TWO_FREAKING":     "example.txt",
  "#TWO_ANNIE":        "example.txt",
  "#TWO_VICEROY":      "example.txt",
  "#TWO_ROBSON":       "example.txt",
  "#TWO_STARS":        "example.txt",
  "#TWO_MYKIND":       "example.txt",
  "#TWO_BOSSONG":      "example.txt",
  "#TWO_SHERRILL":     "example.txt",
  "#TWO_STILLTOGETHER":"example.txt",

  // ── SD ───────────────────────────────────────────────
  "#SD_TITLE":    "example.txt",
  "#SD_BLUEBOY":  "example.txt",
  "#SD_BROTHER":  "example.txt",
  "#SD_LETHERGO": "example.txt",
  "#SD_GOODBYE":  "example.txt",
  "#SD_LETMYBABY":"example.txt",
  "#SD_PASSING":  "example.txt",
  "#SD_TREAT":    "example.txt",
  "#SD_CHAMBER":  "example.txt",
  "#SD_GOEASY":   "example.txt",
  "#SD_ODYSSEY":  "example.txt",

  // ── AO ───────────────────────────────────────────────
  "#AO_WAYYOUDLOVEHER": "example.txt",
  "#AO_TITLE":          "example.txt",
  "#AO_NOOTHERHEART":   "example.txt",
  "#AO_JUSTTOPUT":      "example.txt",
  "#AO_HEARTLIKEHERS":  "example.txt",
  "#AO_WAITING":        "example.txt",
  "#AO_WITHOUTME":      "example.txt",
  "#AO_MYHOUSE":        "example.txt",

  // ── HCTC ─────────────────────────────────────────────
  "#HCTC_TITLE":        "example.txt",
  "#HCTC_NOBODY":       "example.txt",
  "#HCTC_FINALLYALONE": "example.txt",
  "#HCTC_LITTLEDOGS":   "example.txt",
  "#HCTC_PREOCCUPIED":  "example.txt",
  "#HCTC_CHOOCHOO":     "example.txt",
  "#HCTC_K":            "example.txt",
  "#HCTC_HEARTTOHEART": "example.txt",
  "#HCTC_HEYCOWGIRL":   "example.txt",
  "#HCTC_ONTHESQUARE":  "example.txt",
  "#HCTC_YESTERDAYS":   "example.txt",
  "#HCTC_SKYLESS":      "example.txt",
  "#HCTC_BYEBYE":       "example.txt",

  // ── FEHD ─────────────────────────────────────────────
  "#FEHD_GUALALA":    "example.txt",
  "#FEHD_GUALALA2":   "example.txt",
  "#FEHD_CRESCENT":   "example.txt",
  "#FEHD_PORTLAND":   "example.txt",
  "#FEHD_EDMONTON":   "example.txt",
  "#FEHD_CHICAGO":    "example.txt",
  "#FEHD_ROCKAWAY":   "example.txt",
  "#FEHD_VANCOUVER2": "example.txt",
  "#FEHD_VANCOUVER3": "example.txt",
  "#FEHD_VICTORIA":   "example.txt",
  "#FEHD_VISITING":   "example.txt",
  "#FEHD_LASVEGAS":   "example.txt",
  "#FEHD_LA":         "example.txt",
  "#FEHD_CHICAGO2":   "example.txt",

  // ── OWG ──────────────────────────────────────────────
  "#OWG_20180329": "example.txt",
  "#OWG_20180512": "example.txt",
  "#OWG_20180612": "example.txt",

  // ── HN ───────────────────────────────────────────────
  "#HN_INTRO":           "example.txt",
  "#HN_FALLING_BACK":    "example.txt",
  "#HN_TEXTS_GO_GREEN":  "example.txt",
  "#HN_CURRENTS":        "example.txt",
  "#HN_A_KEEPER":        "example.txt",
  "#HN_CALLING_MY_NAME": "example.txt",
  "#HN_STICKY":          "example.txt",
  "#HN_MASSIVE":         "example.txt",
  "#HN_FLIGHTS_BOOKED":  "example.txt",
  "#HN_OVERDRIVE":       "example.txt",
  "#HN_DOWN_HILL":       "example.txt",
  "#HN_TIE_THAT_BINDS":  "example.txt",
  "#HN_LIABILITY":       "example.txt",
  "#HN_JIMMY_COOKS":     "example.txt",

  // ── FD ───────────────────────────────────────────────
  "#FD_VIRGINIA_BEACH":      "example.txt",
  "#FD_AMEN":                "example.txt",
  "#FD_CALLING_FOR_YOU":     "example.txt",
  "#FD_FEAR_OF_HEIGHTS":     "example.txt",
  "#FD_DAYLIGHT":            "example.txt",
  "#FD_FIRST_PERSON_SHOOTER":"example.txt",
  "#FD_IDGAF":               "example.txt",
  "#FD_7969_SANTA":          "example.txt",
  "#FD_SLIME_YOU_OUT":       "example.txt",
  "#FD_BAHAMAS_PROMISES":    "example.txt",
  "#FD_TRIED_OUR_BEST":      "example.txt",
  "#FD_SCREW_THE_WORLD":     "example.txt",
  "#FD_DREW_A_PICASSO":      "example.txt",
  "#FD_MEMBERS_ONLY":        "example.txt",
  "#FD_WHAT_WOULD_PLUTO_DO": "example.txt",
  "#FD_ALL_THE_PARTIES":     "example.txt",
  "#FD_8AM_IN_CHARLOTTE":    "example.txt",
  "#FD_BBL_LOVE":            "example.txt",
  "#FD_GENTLY":              "example.txt",
  "#FD_RICH_BABY_DADDY":     "example.txt",
  "#FD_ANOTHER_LATE_NIGHT":  "example.txt",
  "#FD_AWAY_FROM_HOME":      "example.txt",
  "#FD_POLAR_OPPOSITES":     "example.txt",

  // ── VY ───────────────────────────────────────────────
  "#VY_VOYAGER_INTRO":   "example.txt",
  "#VY_THE_ONE":         "example.txt",
  "#VY_LIKE_A_DREAM":    "example.txt",
  "#VY_WHERE_DO_WE_GO":  "example.txt",
  "#VY_WONDERIN":        "example.txt",
  "#VY_THE_KNIGHT_HAWK": "example.txt",
  "#VY_PURPLE_MOONLIGHT":"example.txt",
  "#VY_VOYAGER_OUTRO":   "example.txt",

  // ── 5E ───────────────────────────────────────────────
  "#5E_OPENING":       "example.txt",
  "#5E_THE_GOOD_TIMES":"example.txt",
  "#5E_WONDERIN":      "example.txt",
  "#5E_CAN_I_VENT":    "example.txt",
  "#5E_THE_KNIGHTS":   "example.txt",
  "#5E_WHERE_DO_WE_GO":"example.txt",
  "#5E_ECHELON":       "example.txt",
  "#5E_CLOSING":       "example.txt",

  // ── JM ───────────────────────────────────────────────
  "#JM_PROLOGUE":         "example.txt",
  "#JM_JELLYFISH":        "example.txt",
  "#JM_THROUGH_THE_WAVES":"example.txt",
  "#JM_MENTALITY":        "example.txt",
  "#JM_FLOATING":         "example.txt",
  "#JM_UNDERWATER_DREAMS":"example.txt",
  "#JM_EPILOGUE":         "example.txt",

  // ── BS ───────────────────────────────────────────────
  "#BS_SCANDALBABY":     "example.txt",
  "#BS_SHOUJOS":         "example.txt",
  "#BS_DOLL":            "example.txt",
  "#BS_KOIMOYOU":        "example.txt",
  "#BS_YUMEMIRUTSUBASA": "example.txt",
  "#BS_HIMAWARI":        "example.txt",
  "#BS_SPACERANGER":     "example.txt",
  "#BS_SAKURAGOODBYE":   "example.txt",
  "#BS_KAGEROU":         "example.txt",
  "#BS_RINGRINGRING":    "example.txt",
  "#BS_LOVESURVIVE":     "example.txt",
  "#BS_PRIDE":           "example.txt",

  // ── TB ───────────────────────────────────────────────
  "#TB_LOVESURVIVE": "example.txt",
  "#TB_HIHIHI":      "example.txt",
  "#TB_GRLISM":      "example.txt",
  "#TB_EVRBSAYEAH":  "example.txt",
  "#TB_SHOUJOS":     "example.txt",
  "#TB_PRIDE":       "example.txt",
  "#TB_GENKI":       "example.txt",
  "#TB_TAIYOU":      "example.txt",
  "#TB_KAGEROU":     "example.txt",
  "#TB_DOLL":        "example.txt",
  "#TB_NAMIDA":      "example.txt",
  "#TB_MIDNIGHT":    "example.txt",
  "#TB_SHUNKAN":     "example.txt",
  "#TB_SAKURA":      "example.txt",

  // ── BA ───────────────────────────────────────────────
  "#BA_GLAMOROUS":   "example.txt",
  "#BA_BABYACTION":  "example.txt",
  "#BA_LOVESURVIVE": "example.txt",
  "#BA_PRIDE":       "example.txt",
  "#BA_HARUKAZE":    "example.txt",
  "#BA_BURN":        "example.txt",
  "#BA_WELCOME":     "example.txt",
  "#BA_ONEPIECE":    "example.txt",
  "#BA_KIMITODO":    "example.txt",
  "#BA_TOKYO":       "example.txt",
  "#BA_SATISFACTION":"example.txt",
  "#BA_NAMIDAYO":    "example.txt",

  // ── QAT ──────────────────────────────────────────────
  "#QAT_TITLE":    "example.txt",
  "#QAT_ROCK":     "example.txt",
  "#QAT_PINHEEL":  "example.txt",
  "#QAT_HARUKAZE": "example.txt",
  "#QAT_TAIYOU":   "example.txt",
  "#QAT_RISING":   "example.txt",
  "#QAT_BRIGHT":   "example.txt",
  "#QAT_KILL":     "example.txt",
  "#QAT_PIZZA":    "example.txt",
  "#QAT_PLAYBOY":  "example.txt",
  "#QAT_EMOTION":  "example.txt",
  "#QAT_RIGHT":    "example.txt",

  // ── ST (Speed) ───────────────────────────────────────
  "#ST_BNW":       "example.txt",
  "#ST_OVERDRIVE": "example.txt",
  "#ST_AWANAI":    "example.txt",
  "#ST_STANDARD":  "example.txt",
  "#ST_WEATHER":   "example.txt",
  "#ST_KAGEN":     "example.txt",
  "#ST_YOURSONG":  "example.txt",
  "#ST_GRAD":      "example.txt",
  "#ST_KOE":       "example.txt",
  "#ST_RUNNERS":   "example.txt",
  "#ST_KIMIMIRAI": "example.txt",
  "#ST_NAMIDA":    "example.txt",

  // ── HW ───────────────────────────────────────────────
  "#HW_IMAGE":     "example.txt",
  "#HW_YOURSONG":  "example.txt",
  "#HW_LOVE":      "example.txt",
  "#HW_DEPARTURE": "example.txt",
  "#HW_GRAD":      "example.txt",
  "#HW_OYASUMI":   "example.txt",
  "#HW_PLACE":     "example.txt",
  "#HW_WINTER":    "example.txt",
  "#HW_NAV":       "example.txt",
  "#HW_RUNNERS":   "example.txt",
  "#HW_KIMIMIRAI": "example.txt",
  "#HW_TITLE":     "example.txt",

  // ── Y ────────────────────────────────────────────────
  "#Y_ROOM7":    "example.txt",
  "#Y_STAMP":    "example.txt",
  "#Y_LOVEMEDO": "example.txt",
  "#Y_MORNING":  "example.txt",
  "#Y_SUNDAY":   "example.txt",
  "#Y_HEAVEN":   "example.txt",
  "#Y_TITLE":    "example.txt",
  "#Y_YOURSONG": "example.txt",
  "#Y_INST":     "example.txt",
  "#Y_AMDKJ":    "example.txt",

  // ── HM ───────────────────────────────────────────────
  "#HM_PLATFORM":  "example.txt",
  "#HM_FLASHBACK": "example.txt",
  "#HM_UNIVERSE":  "example.txt",
  "#HM_OVER":      "example.txt",
  "#HM_TAKEMEOUT": "example.txt",
  "#HM_FUTARI":    "example.txt",
  "#HM_ELECTRIC":  "example.txt",
  "#HM_TONARI":    "example.txt",
  "#HM_TONIGHT":   "example.txt",
  "#HM_TITLE":     "example.txt",

  // ── KFTD ─────────────────────────────────────────────
  "#KFTD_TONIGHT":     "example.txt",
  "#KFTD_MASTERPIECE": "example.txt",
  "#KFTD_MABATAKI":    "example.txt",
  "#KFTD_SAISHU":      "example.txt",
  "#KFTD_AMDKJ":       "example.txt",
  "#KFTD_LOVEMEDO":    "example.txt",
  "#KFTD_FUZZY":       "example.txt",
  "#KFTD_GRAVITY":     "example.txt",
  "#KFTD_RULE":        "example.txt",
  "#KFTD_CEREMONY":    "example.txt",

  // ── MIRROR ───────────────────────────────────────────
  "#MIRROR_AI":      "example.txt",
  "#MIRROR_YUME":    "example.txt",
  "#MIRROR_TITLE":   "example.txt",
  "#MIRROR_ONEMORE": "example.txt",
  "#MIRROR_CITY":    "example.txt",
  "#MIRROR_IVORY":   "example.txt",
  "#MIRROR_WAVE":    "example.txt",
  "#MIRROR_AMBER":   "example.txt",
  "#MIRROR_PRISM":   "example.txt",
  "#MIRROR_CIRCLE":  "example.txt",

  // ── LUM ──────────────────────────────────────────────
  "#LUM_TITLE":     "example.txt",
  "#LUM_LINE":      "example.txt",
  "#LUM_HIGHLIGHT": "example.txt",
  "#LUM_VISION":    "example.txt",
  "#LUM_ANSWER":    "example.txt",
  "#LUM_PLUM":      "example.txt",
  "#LUM_LOOP":      "example.txt",
  "#LUM_BRIGHT":    "example.txt",
  "#LUM_SOUNDLY":   "example.txt",
  "#LUM_ETERNAL":   "example.txt",

  // ── YAN ($) ──────────────────────────────────────────
  "$YAN_CHAK": "example.txt",
  "$YAN_GARD": "example.txt",
  "$YAN_NB":   "example.txt",
  "$YAN_VIB":  "example.txt",
  "$YAN_EASY": "example.txt",
  "$YAN_BRO":  "example.txt",
  "$YAN_LG":   "example.txt",
  "$YAN_YAN":  "example.txt",
  "$YAN_VC":   "example.txt",
  "$YAN_NNN":  "example.txt",
  "$YAN_BN":   "example.txt",
  "$YAN_TL":   "example.txt",
  "$YAN_ITF":  "example.txt",

  // ── TG ($) ───────────────────────────────────────────
  "$TG_NNN": "example.txt",
  "$TG_TG":  "example.txt",
  "$TG_WAT": "example.txt",
  "$TG_COS": "example.txt",
  "$TG_FG":  "example.txt",
  "$TG_GC":  "example.txt",
  "$TG_EWN": "example.txt",
  "$TG_HO":  "example.txt",
  "$TG_UTG": "example.txt",
  "$TG_JIL": "example.txt",

  // ── EA ($) ───────────────────────────────────────────
  "$EA_LETSGO":            "example.txt",
  "$EA_BANDS":             "example.txt",
  "$EA_YOUA10":            "example.txt",
  "$EA_PUTTHATMONEYUP":    "example.txt",
  "$EA_BLUETIPS":          "example.txt",
  "$EA_STICKY":            "example.txt",
  "$EA_TAKEMYCAKE":        "example.txt",
  "$EA_ALLMYGUAP":         "example.txt",
  "$EA_KEEPITREAL":        "example.txt",
  "$EA_DIAMONDS":          "example.txt",
  "$EA_OFCOURSE":          "example.txt",
  "$EA_1600RAGERANTHEM":   "example.txt",
  "$EA_NOTTHESAME":        "example.txt",
  "$EA_CLOSURE":           "example.txt",
  "$EA_EXTRAEDOUT":        "example.txt",
  "$EA_RUNITUP":           "example.txt",
  "$EA_EXTRANEWPATEK":     "example.txt",
  "$EA_EXTRATHEENDISNEAR": "example.txt",

  // ── 1629 ($) ─────────────────────────────────────────
  "$1629_INTRO":        "example.txt",
  "$1629_FELLINLUV":    "example.txt",
  "$1629_NOSTYLIST":    "example.txt",
  "$1629_DRIPSEASON":   "example.txt",
  "$1629_TWINTURBOS":   "example.txt",
  "$1629_SLATTWALK":    "example.txt",
  "$1629_ONSITE":       "example.txt",
  "$1629_ROCKSTARSHIT": "example.txt",
  "$1629_PURPLEHAZE":   "example.txt",
  "$1629_RAGER4LIFE":   "example.txt",
  "$1629_NOCEILINGS":   "example.txt",
  "$1629_ETERNALRAGE":  "example.txt",
  "$1629_ICEDOUTHALO":  "example.txt",
  "$1629_CARTISEASON":  "example.txt",
  "$1629_OUTRO":        "example.txt",

  // ── BAS ($) ──────────────────────────────────────────
  "$BAS_BAS": "example.txt",
  "$BAS_SEV": "example.txt",
  "$BAS_OT":  "example.txt",
  "$BAS_FR":  "example.txt",
  "$BAS_BL":  "example.txt",
  "$BAS_PF":  "example.txt",
  "$BAS_PAR": "example.txt",
  "$BAS_SID": "example.txt",
  "$BAS_AM":  "example.txt",
  "$BAS_VW":  "example.txt",
  "$BAS_SES": "example.txt",
  "$BAS_SAR": "example.txt",
  "$BAS_JB":  "example.txt",
  "$BAS_TIN": "example.txt",
  "$BAS_ING": "example.txt",

  // ── MM ($) ───────────────────────────────────────────
  "$MM_SLK":   "example.txt",
  "$MM_CE":    "example.txt",
  "$MM_PH":    "example.txt",
  "$MM_HND":   "example.txt",
  "$MM_AZ":    "example.txt",
  "$MM_MG":    "example.txt",
  "$MM_BF":    "example.txt",
  "$MM_HC":    "example.txt",
  "$MM_AA":    "example.txt",
  "$MM_RT":    "example.txt",
  "$MM_NOV":   "example.txt",
  "$MM_STR":   "example.txt",
  "$MM_SC":    "example.txt",
  "$MM_SCR":   "example.txt",
  "$MM_FIAB":  "example.txt",
  "$MM_SOL":   "example.txt",
  "$MM_BG":    "example.txt",
  "$MM_627":   "example.txt",
  "$MM_DAISY": "example.txt",
  "$MM_MM":    "example.txt",

  // ── SYN ($) ──────────────────────────────────────────
  "$SYN_BOH": "example.txt",

  // ── R5 ($) ───────────────────────────────────────────
  "$R5_R5DOTHATSHIT": "example.txt",

  // ── PS ($) ───────────────────────────────────────────
  "$PS_HW":       "example.txt",
  "$PS_CW":       "example.txt",
  "$PS_BF":       "example.txt",
  "$PS_BM":       "example.txt",
  "$PS_ISH":      "example.txt",
  "$PS_YK":       "example.txt",
  "$PS_BEAUTEEN": "example.txt",
  "$PS_MC":       "example.txt",
  "$PS_PW":       "example.txt",

};
